apiVersion: v2
name: caa-csi-block-driver
description: A CSI block driver for Confidential Containers Peer Pods
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/confidential-devhub/caa-csi-block-driver
sources:
  - https://github.com/confidential-devhub/caa-csi-block-driver
keywords:
  - csi
  - confidential-containers
  - peer-pods
  - storage
maintainers:
  - name: Mohammed Adnan
