apiVersion: v2
name: caa-csi-block-driver
description: CSI block volume driver for Confidential Containers (peer pods)
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/confidential-devhub/caa-csi-block-driver
sources:
  - https://github.com/confidential-devhub/caa-csi-block-driver
keywords:
  - csi
  - confidential-containers
  - peer-pods
  - block-storage
maintainers:
  - name: Mohammed Adnan
    url: https://github.com/mohammedadnan21
